#
# JDBC properties
#
#spring.datasource.url=jdbc:oracle:thin:@//oradb11-test.bog.ge:1521/TRAINDB
#spring.datasource.username=hr
#spring.datasource.password=hr
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


##########################################################
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory?useSSL=false&serverTimezone=UTC

# Database username and password
spring.datasource.username=springstudent
spring.datasource.password=springstudent

#
#
#
#securtiy
spring.security.user.name=luka
spring.security.user.password=test