#
# JDBC properties
#
spring.datasource.url=jdbc:oracle:thin:@//oradb11-test.bog.ge:1521/TRAINDB
spring.datasource.username=hr
spring.datasource.password=hr
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#
#
#
#securtiy
spring.security.user.name=luka
spring.security.user.password=test