spring.application.name=OracleCRUDApp
spring.datasource.xldr.url=jdbc:bog-wrapper:oracle:thin:@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(Host = exa101)(Port = 1521)))(CONNECT_DATA = (SERVICE_NAME = XL03)))
spring.datasource.xldr.driver-class-name=ge.bog.commons.jdbc.wrapper.JdbcOracleDriver
spring.datasource.xldr.username=fors
spring.datasource.xldr.password=fors77
server.port=8084