spring.application.name=companyms

server.port=8084

#H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console-test
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=test
spring.datasource.password=test