spring.application.name=spring-data-jpa-example

#Oracle database properties
spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=oradb11-test.bog.ge)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=TRAINDB)(SERVER=DEDICATED)))
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.username=hr
spring.datasource.password=hr