spring.application.name=limits-microservices-config-server
server.port=8888

spring.cloud.config.server.git.uri=file:///C:/Users/lmekudishvili/Desktop/Spring/Microservices/In28Minutes/Section5/limits-service-global-config-properties
spring.cloud.config.server.git.default-label=dev
