spring.application.name=ProductsMicroservice
server.port=0

#spring.kafka.producer.bootstrap-servers=172.28.87.110:9092,172.28.87.110:9094
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.bootstrap-servers=172.28.87.110:9092,172.28.87.110:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
product.created.events.topic=product-created-events-topic
spring.kafka.producer.acks=all

#if producer fail to send message it will try 10 times with 3 seconds interval to retry sending with below properties
#spring.kafka.producer.retries=10
#spring.kafka.producer.properties.retry.backoff.ms=3000


#or we can make those properties instead of above 2
#this property will set maximum amount of time in ms that producer will wait to complete the entire send operation ->
# ->(including send message, get acknowledgments from all replicas, if failed-also retry operations)
spring.kafka.producer.properties.delivery.timeout.ms=120000
#this will set time that producer wait before send, this lets us make producer wait and send message as a batch
#when it's set to 0, means that producer will not wait and send message as soon as it receives it
spring.kafka.producer.properties.linger.ms=0
#this property is how much time the producer will wait after sending message to get response from broker
spring.kafka.producer.properties.request.timeout.ms=3000

#idempotence
spring.kafka.producer.properties.enable.idempotence=true