spring.application.name=Products-Microservice
server.port=0
spring.kafka.producer.bootstrap-servers=172.28.87.110:9092,172.28.87.110:9094
spring.kafka.topic.product-created.topic=product-created-topic
spring.kafka.topic.product-created.partitions=3
spring.kafka.topic.product-created.replicas=3
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
#spring.kafka.producer.retries=10
##3second interval 10 times
#spring.kafka.producer.properties.retry.backoff.ms=3000

# max amount of time producer will wait to receive response from all in-sync replicas, also retries and all operations
spring.kafka.producer.properties.delivery.timeout.ms=120000
#time to wait producer collect messages and then send them as a batch
spring.kafka.producer.properties.linger.ms=0
#how much time to wait producer to broker to receive message  after sending a single request
spring.kafka.producer.properties.request.timeout.ms=30000