spring.application.name=springBootBackend

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/ems?useSSL=false
spring.datasource.username=springstudent
spring.datasource.password=springstudent

#Hibernate properties
spring.jpa.hibernate.ddl-auto=update

spring.main.banner-mode=LOG